# Generated by Django 4.0.3 on 2022-03-11 11:29

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackernews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hackernews_id', models.IntegerField(null=True)),
                ('title', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('by', models.CharField(max_length=200)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('indexed_time', models.DateTimeField(null=True)),
                ('published_time', models.IntegerField(null=True)),
                ('url', models.TextField()),
            ],
        ),
    ]
