# Generated by Django 4.0.3 on 2022-03-11 15:14

from django.db import migrations, models
import hackernews.models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackernews',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='id',
            field=models.CharField(default=hackernews.models.generate_unique_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
